#!/usr/bin/env bash

if [ -d .git ] ; then 
  touch README.md .gitignore 
  ln -s README.md README 
  git add README README.md .gitignore 
  git commit -m 'Initial Commit'
else
  echo "Must be in the root of a git repository"
fi

